print('WELCOME KAYODE')
print('STAY FOCUSED BOY YOU CAN DO IT')
# TO SAVE THIS NEXT LINE TO YOU REPOSITORY YOU SIMPLY RIGHT CLICK THE YOU WILL SELECT GIT AND YOU THEN COMMIT IT
# WE HAVE TWO TYPES OF REPOSITORY THERE ARE THE LOCAL REPO AND THE REMOTE REPO (THE ONE WE SEE ON GITHUB)
#WHEN EVER WE ONLY COMMIT A FILE , IT ONLY REFLECT ON THE LOCAL REPO AND NOT THE REMOTE REPO
# TO COMMIT IT TO THE REMOTE REPO TOO WE SIMPLY SELECT THE COMMIT AND PUSH